INSERT INTO books VALUES(7586902,'The Good Man','Leo Penrose');
INSERT INTO books VALUES(7138,'The Good Woman','Ivory Murphy-Penrose');
insert into books (ibn, title, author) values (1, 'President''s Lady, The', 'Sumner Piggens');
insert into books (ibn, title, author) values (2, 'Thunderpants', 'Wilmar Lauritsen');
insert into books (ibn, title, author) values (3, 'Planet of the Apes', 'Guinna Skirrow');
insert into books (ibn, title, author) values (4, 'Before the Rains', 'Caro Sterman');
insert into books (ibn, title, author) values (5, 'Grand Tour: Disaster in Time (Timescape)', 'Ada Currey');
insert into books (ibn, title, author) values (6, 'Big Knife, The', 'Cherlyn Dobie');
insert into books (ibn, title, author) values (7, 'Comet in Moominland', 'Alyda Twidale');
insert into books (ibn, title, author) values (8, 'Greatest, The', 'Lynna Marquess');
insert into books (ibn, title, author) values (9, '13 Assassins (Jûsan-nin no shikaku)', 'Katerina Torricina');
insert into books (ibn, title, author) values (10, 'Heaven Knows, Mr. Allison', 'Rina Vice');
insert into books (ibn, title, author) values (11, 'American Soldiers', 'Meriel Berryann');
insert into books (ibn, title, author) values (12, 'Being Human', 'Chris Knotte');
insert into books (ibn, title, author) values (13, 'Rosencrantz and Guildenstern Are Dead', 'Roxie Mathiassen');
insert into books (ibn, title, author) values (14, 'Robinson in Space', 'Lulita Daynter');
insert into books (ibn, title, author) values (15, 'Crooked Arrows', 'Karlene Davidek');
